// generated by src/lib/blog.gen.ts

import type {Blog_Feed} from '@ryanatkn/fuz_blog/blog.js';

export const feed: Blog_Feed = {
	title: 'webdevladder.net blog',
	id: 'https://www.webdevladder.net/',
	home_page_url: 'https://www.webdevladder.net/',
	description: 'blog of a web developer building free and open source tools and toys',
	icon: 'https://www.webdevladder.net/favicon.png',
	favicon: 'https://www.webdevladder.net/favicon.png',
	author: {name: 'Ryan Atkinson', url: 'https://www.ryanatkn.com/', email: 'mail@ryanatkn.com'},
	atom: {feed_url: 'https://www.webdevladder.net/blog/feed.xml'},
	items: [
		{
			id: 'https://www.webdevladder.net/blog/1',
			url: 'https://www.webdevladder.net/blog/hello-webdevladder-blog',
			blog_post_id: 1,
			title: 'Hello webdevladder blog',
			slug: 'hello-webdevladder-blog',
			date_published: '2024-07-10T22:07:32.473Z',
			date_modified: '2024-07-10T22:07:32.473Z',
			summary: "creating webdevladder's blog",
			tags: ['webdev', 'svelte', 'typescript', 'sveltekit', 'vite'],
			comments: {url: 'https://mastodon.social/@webdevladder/112764548975084845', type: 'mastodon'},
		},
	],
};

// generated by src/lib/blog.gen.ts
