// generated by src/lib/blog.gen.ts

import type {Blog_Feed} from '@ryanatkn/fuz_blog/blog.js';

export const feed: Blog_Feed = {
	title: 'webdevladder.net blog',
	id: 'https://www.webdevladder.net/',
	home_page_url: 'https://www.webdevladder.net/',
	description: 'blog of a web developer building free and open source tools and toys',
	icon: 'https://www.webdevladder.net/favicon.png',
	favicon: 'https://www.webdevladder.net/favicon.png',
	author: {name: 'Ryan Atkinson', url: 'https://www.ryanatkn.com/', email: 'mail@ryanatkn.com'},
	atom: {feed_url: 'https://www.webdevladder.net/blog/feed.xml'},
	items: [
		{
			id: 'https://www.webdevladder.net/blog/1',
			url: 'https://www.webdevladder.net/blog/hello-webdevladder-blog',
			blog_post_id: 1,
			title: 'Hello webdevladder blog',
			slug: 'hello-webdevladder-blog',
			date_published: '2024-07-10T22:07:32.473Z',
			date_modified: '2024-07-10T23:06:38.928Z',
			summary: "creating webdevladder's blog",
			tags: ['webdev', 'svelte', 'typescript', 'sveltekit', 'vite'],
			comments: {type: 'mastodon', url: 'https://fosstodon.org/@webdevladder/113312147463274655'},
		},
		{
			id: 'https://www.webdevladder.net/blog/2',
			url: 'https://www.webdevladder.net/blog/introducing-webdevladder',
			blog_post_id: 2,
			title: 'Introducing webdevladder',
			slug: 'introducing-webdevladder',
			date_published: '2024-08-14T18:10:26.092Z',
			date_modified: '2025-06-27T15:24:37.363Z',
			summary:
				'I describe the purpose of my YouTube channel and blog, webdevladder, and my plans for the future',
			tags: ['webdevladder'],
			comments: {type: 'mastodon', url: 'https://fosstodon.org/@webdevladder/113312132188029470'},
		},
		{
			id: 'https://www.webdevladder.net/blog/3',
			url: 'https://www.webdevladder.net/blog/svelte-5-signals-fix-its-glitchy-and-inconsistent-reactivity',
			blog_post_id: 3,
			title: 'Svelte 5 signals fix its glitchy and inconsistent reactivity',
			slug: 'svelte-5-signals-fix-its-glitchy-and-inconsistent-reactivity',
			date_published: '2024-08-15T12:53:55.522Z',
			date_modified: '2024-08-15T12:53:55.522Z',
			summary:
				'Svelte 5 adopted signals to replace its old reactivity system that had some subtle but important problems',
			tags: ['svelte', 'signals'],
			comments: {type: 'mastodon', url: 'https://fosstodon.org/@webdevladder/113312123824800794'},
		},
	],
};

// generated by src/lib/blog.gen.ts
