// generated by src/lib/blog.gen.ts

import type {Blog_Feed} from '@ryanatkn/fuz_blog/blog.js';

export const feed: Blog_Feed = {
	title: "Ryan Atkinson's blog",
	id: 'https://www.webdevladder.net/',
	home_page_url: 'https://www.webdevladder.net/',
	description: 'blog of a web developer building free and open source tools and toys',
	icon: 'https://www.webdevladder.net/favicon.png',
	favicon: 'https://www.webdevladder.net/favicon.png',
	author: {name: 'Ryan Atkinson', url: 'https://www.ryanatkn.com/', email: 'mail@ryanatkn.com'},
	atom: {feed_url: 'https://www.webdevladder.net/blog/feed.xml'},
	items: [],
};

// generated by src/lib/blog.gen.ts
